### PR TITLE
replace custom error printing with std macro

### PR DESCRIPTION
**Pull request by nivkner**

### CODE REVIEW

**Comment by dpc** [comment]
Thanks! (also for the other PR). There are more places using the existing macro (see Travis build log).

**Comment by nivkner** [comment]
Travis fails on 1.18 because `eprintln` was added in 1.19. Should I change the version Travis.yml?

**Comment by dpc** [comment]
I consider the minimum compiler version bump to be a breaking change. Which is OK, since `master` is development branch and until actually 3.0.0 something is released, we're free to break anything anytime. :)

**Comment by dpc** [comment]
I bumped the version.

**Comment by dpc** [comment]
I've restarted the build, and will merge once it passes. Thanks!

**Comment by nivkner** [comment]
I don't think the build restarted since I'm still seeing rust 1.18 in the build log.

**Comment by dpc** [comment]
I just merged. Thanks!

**Pull request merged**
