### PR TITLE
Support Folder Nesting Configuration

### LINKED ISSUE #43: Configurable chunks folder nesting (e.g. flat) for faster sync?
Modern filesystems can have more than 64k files in them, as do many cloud storage systems.

Due to the two-level chunk folder organization, even a small backup can end up with a lot of folders.  Trying to sync a tree with about 1k folders to Google Drive (using rclone) takes forever because it has to issue a separate HTTP/API request for each folder to list the chunks for sync.

Can we have a configuration to select the nesting-level of the chunks folder?  It could default to two as current, but go down to zero where it's a single folder with all chunks contained.

### PR DESCRIPTION
**Pull request by phillipCouto**
This is a WIP for now, it is functioning but I want to setup a proper test case that will verify all options are working correctly with the changes.

@dpc not sure if you want to take a peek and see what I have done so far.

Should we limit how deep the nesting level can be? I have it set to not surpass the size of the digest so it doesn't crash but nesting at 31 is not practical at all and can generate a ton of metadata for a file system.

Closes #43.

### CODE REVIEW

**Comment by dpc** [comment]
LGTM

**Comment by phillipCouto** [comment]
@dpc this is ready for final review. I added a unit test to test a range of settings to make sure all features function correctly.

**Comment by dpc** [comment]
Awesome!

**Comment by phillipCouto** [comment]
Thank you =)

**Pull request merged**
