### PR TITLE
Integrate `slog` and optimize processing

### PR DESCRIPTION
**Pull request by dpc**
This change:

* adds a `stderr` debug output (turned on by `-DD`) that prints statistics of different parts of the pipeline; this is based on `slog`
* Moves processing threads to be shared between different layers of writting stuff (data, vs index, vs index of an index and so on)

### CODE REVIEW

**Comment by dpc** [comment]
```
Mar 27 00:50:16.881 DEBG total time, name: input-reader, input: 0.275241757, inside: 0, output: 4.99729611
Mar 27 00:50:16.898 DEBG total time, name: chunker, input: 0, inside: 3.789896676, output: 1.499951845
Mar 27 00:50:16.913 DEBG total time, name: chunker, input: 0, inside: 0.001270074, output: 0.00000522
Mar 27 00:50:16.915 DEBG total time, name: chunker, input: 0, inside: 0.000003259, output: 0.000002716
Mar 27 00:50:16.915 DEBG total time, name: chunk-processing, input: 0.292956768, inside: 3.399154403, output: 0.169168692
Mar 27 00:50:16.915 DEBG total time, name: chunk-processing, input: 0.319576917, inside: 3.313578766, output: 0.200596487
Mar 27 00:50:16.915 DEBG total time, name: chunk-processing, input: 0.361151046, inside: 3.355589657, output: 0.19483244
Mar 27 00:50:16.915 DEBG total time, name: chunk-processing, input: 0.303446365, inside: 3.36682324, output: 0.196335971
Mar 27 00:50:16.915 DEBG total time, name: chunk-processing, input: 0.280932044, inside: 3.384652279, output: 0.175253461
Mar 27 00:50:16.915 DEBG total time, name: chunk-processing, input: 0.346162129, inside: 3.319742591, output: 0.202955268
Mar 27 00:50:16.915 DEBG total time, name: chunk-processing, input: 0.371646506, inside: 3.268694323, output: 0.191890475
Mar 27 00:50:16.915 DEBG total time, name: chunk-processing, input: 0.373532858, inside: 3.303381288, output: 0.206956405
Mar 27 00:50:16.916 DEBG total time, name: chunk-writer, input: 2.047794657, inside: 0.007015684, output: 3.022296424
Mar 27 00:50:16.916 DEBG total time, name: chunk-writer, input: 2.017267334, inside: 0.008629837, output: 3.035579557
Mar 27 00:50:16.916 DEBG total time, name: chunk-writer, input: 1.947680025, inside: 0.011072365, output: 3.12289643
Mar 27 00:50:16.916 DEBG total time, name: chunk-writer, input: 2.019253091, inside: 0.007773392, output: 3.023358422
Mar 27 00:50:16.916 DEBG total time, name: chunk-writer, input: 1.996347012, inside: 0.007175387, output: 3.024432189
Mar 27 00:50:16.916 DEBG total time, name: chunk-writer, input: 1.960666937, inside: 0.009207693, output: 3.130593181
Mar 27 00:50:16.916 DEBG total time, name: chunk-writer, input: 1.954009211, inside: 0.007468766, output: 3.120896913
Mar 27 00:50:16.916 DEBG total time, name: chunk-writer, input: 1.9182583979999999, inside: 0.009935819, output: 3.144717457
Mar 27 00:50:16.916 DEBG total time, name: chunk-writer, input: 2.027257507, inside: 0.011544737, output: 3.025744777
Mar 27 00:50:16.916 DEBG total time, name: chunk-writer, input: 1.9720208160000001, inside: 0.008453063, output: 3.095835579
Mar 27 00:50:16.916 DEBG total time, name: chunk-writer, input: 2.005423676, inside: 0.007767261, output: 3.088617266
Mar 27 00:50:16.916 DEBG total time, name: chunk-writer, input: 2.101607127, inside: 0.009224682, output: 2.9548790670000002
Mar 27 00:50:16.916 DEBG total time, name: chunk-writer, input: 2.035699316, inside: 0.009466324, output: 3.033608977
Mar 27 00:50:16.917 DEBG total time, name: chunk-writer, input: 1.9795898360000002, inside: 0.008773129, output: 3.094386792
Mar 27 00:50:16.917 DEBG total time, name: chunk-writer, input: 1.998922007, inside: 0.012034313, output: 3.065181996
Mar 27 00:50:16.917 DEBG total time, name: chunk-writer, input: 1.9780458890000001, inside: 0.008932057, output: 3.068666704
Mar 27 00:50:16.917 DEBG total time, name: chunk-writer, input: 1.975396149, inside: 0.008740197, output: 3.103861503
Mar 27 00:50:16.917 DEBG total time, name: chunk-writer, input: 1.969111874, inside: 0.008072097, output: 3.084496672
Mar 27 00:50:16.917 DEBG total time, name: chunk-writer, input: 1.907560108, inside: 0.007786298, output: 3.152791402
Mar 27 00:50:16.918 DEBG total time, name: chunk-writer, input: 1.963039593, inside: 0.006245812, output: 3.109149197
Mar 27 00:50:16.919 DEBG total time, name: chunk-writer, input: 2.035228701, inside: 0.007831803, output: 3.047595091
Mar 27 00:50:16.919 DEBG total time, name: chunk-writer, input: 1.9642380350000002, inside: 0.00838261, output: 3.125410881
Mar 27 00:50:16.919 DEBG total time, name: chunk-writer, input: 2.073952716, inside: 0.007454814, output: 2.997360851
Mar 27 00:50:16.919 DEBG total time, name: chunk-writer, input: 2.038837206, inside: 0.009370699, output: 3.015478127
Mar 27 00:50:16.920 DEBG total time, name: chunk-writer, input: 1.93415318, inside: 0.010558582, output: 3.10626627
Mar 27 00:50:16.920 DEBG total time, name: chunk-writer, input: 2.051171855, inside: 0.008108599, output: 3.006801985
Mar 27 00:50:16.920 DEBG total time, name: chunk-writer, input: 1.983484855, inside: 0.009940781, output: 3.090971911
Mar 27 00:50:16.920 DEBG total time, name: chunk-writer, input: 1.991379784, inside: 0.009818712, output: 3.060846779
Mar 27 00:50:16.920 DEBG total time, name: chunk-writer, input: 2.02569217, inside: 0.008326698, output: 3.014509869
Mar 27 00:50:16.923 DEBG total time, name: chunk-writer, input: 2.055406248, inside: 0.010434317, output: 3.018590681
Mar 27 00:50:16.923 DEBG total time, name: chunk-writer, input: 1.989486888, inside: 0.010648274, output: 3.081730459
Mar 27 00:50:16.928 DEBG total time, name: chunk-writer, input: 2.040859497, inside: 0.013481347, output: 3.055903415

```

According to these the bottleneck on my stresstest is already on chunking function, which is fast but single-threaded.

**Comment by aidanhs** [comment]
Can you note down the commands you ran to get the output above? I've built your branch and can probably get there in the end, but want to make sure I'm doing it right.

Some thoughts:
 - rsroll is [competitive with bup itself](https://github.com/aidanhs/rollsum-tests) (I do need to redo those benchmarks, but I don't expect massive changes from where they are at the moment), which is probably the most widely used and optimized chunking algorithm out there aside from rsync itself (which bup is based on)
 - rabin is based on [crc](https://en.wikipedia.org/wiki/Cyclic_redundancy_check). Intuitively I'd expect that to be pretty quick, but a quick look at some C++ code I wrote for doing seems to have it doing more work than bupsplit...so I'm not sure which would be faster. I can add it and see :)
 - looking at the rollsum-tests benchmarks, it's probably possible to squeeze an extra 10% performance out of rsroll
 - you can actually parallelise rolling checksums - pick a few offsets (call them 'superchunks') and run the rolling sum from each of the locations, populating a vector with the splits from each offset. Since the splits depend only on the N bytes at that location, they can be used regardless of where the rollsum started from. Two things to be aware of though - the superchunks must overlap to check for a split location straddling a superchunk boundary, and you need to handle splitting too-large chunks very carefully (I assume you do have some cap on chunk size in rdedup?)

I'll update the benchmarks this weekend and look at rabin. Unfortunately the rabin implementations I've found in the wild have tended to be quite low quality (i.e. they're wrong) so it remains to be seen how confident I end up being in the algorithm correctness (I'm pretty confident with bupsplit courtesy of the random data benchmarks).

**Comment by aidanhs** [comment]
So, here's a script I used for doing my own benchmark:
```
#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset

set -o xtrace

if [ ! -f random.data ]; then
    dd if=/dev/urandom bs=1M count=200 of=random.data
fi
cargo build --release
randomfile=$(pwd)/random.data
rdedup="$(pwd)/target/release/rdedup --dir rdtest/ram"
if [ ! -d rdtest ]; then
    mkdir rdtest
    sudo mount -t ramfs ramfs ./rdtest
    sudo chown -R $(whoami): ./rdtest
fi
if [ ! -d rdtest/ram ]; then
    $rdedup init
fi
$rdedup rm a || true
if [ "$($rdedup ls)" != "" ]; then
    echo files remaining
    exit 1
fi
$rdedup gc
cat $randomfile > /dev/null # get randomfile into memory
<$randomfile /usr/bin/time -v $rdedup -D -D store a
```
It uses a ramdisk to eliminate the overhead of IO and makes sure the file is cached in memory. With this script, the output is as follows:
```
[...]
+ /usr/bin/time -v /tmp/tmp.YRfyGQboNT/rdedup/target/release/rdedup --dir rdtest/ram -D -D store a
Mar 28 15:51:32.752 INFO Writing data, name: a
Mar 28 15:51:41.480 DEBG total time, name: input-reader, input: 0.154518002, inside: 0, output: 8.567178384
Mar 28 15:51:41.511 DEBG total time, name: chunker, input: 0, inside: 2.457480325, output: 6.298448002
Mar 28 15:51:41.563 DEBG total time, name: chunker, input: 0, inside: 0.001371341, output: 0.000014308
Mar 28 15:51:41.565 DEBG total time, name: chunk-processing, input: 0.32609713, inside: 7.349747228, output: 0.027601529
Mar 28 15:51:41.566 DEBG total time, name: chunk-processing, input: 0.013784122, inside: 7.614507716, output: 0.076064281
Mar 28 15:51:41.566 DEBG total time, name: chunk-processing, input: 0.017297419, inside: 7.598728364, output: 0.022569882
Mar 28 15:51:41.566 DEBG total time, name: chunk-processing, input: 0.244928232, inside: 7.403482009, output: 0.031525278
Mar 28 15:51:41.567 DEBG total time, name: chunk-writer, input: 8.774024339, inside: 0.008563565, output: 0.000084971
Mar 28 15:51:41.568 DEBG total time, name: chunk-writer, input: 8.772722625, inside: 0.009914988, output: 0.000087275
Mar 28 15:51:41.568 DEBG total time, name: chunk-writer, input: 8.774884688, inside: 0.008055327, output: 0.000083256
Mar 28 15:51:41.569 DEBG total time, name: chunk-writer, input: 8.793702999, inside: 0.010203523, output: 0.000084203
Mar 28 15:51:41.569 DEBG total time, name: chunk-writer, input: 8.780794379, inside: 0.007791244, output: 0.0000813
Mar 28 15:51:41.569 DEBG total time, name: chunk-writer, input: 8.78268749, inside: 0.007292319, output: 0.000084567
Mar 28 15:51:41.570 DEBG total time, name: chunk-writer, input: 8.775765983, inside: 0.008608537, output: 0.00008685
Mar 28 15:51:41.570 DEBG total time, name: chunk-writer, input: 8.794078721, inside: 0.008606836, output: 0.000084872
Mar 28 15:51:41.571 DEBG total time, name: chunk-writer, input: 8.796841063, inside: 0.008038436, output: 0.000084486
Mar 28 15:51:41.571 DEBG total time, name: chunk-writer, input: 8.772815551, inside: 0.011293473, output: 0.000091998
Mar 28 15:51:41.572 DEBG total time, name: chunk-writer, input: 8.775592793, inside: 0.009698541, output: 0.000082456
Mar 28 15:51:41.572 DEBG total time, name: chunk-writer, input: 8.776176515, inside: 0.00815626, output: 0.000091681893 new chunks

209904517 new bytes
Mar 28 15:51:41.573 DEBG total time, name: chunk-writer, input: 8.775961187, inside: 0.01019498, output: 0.000080037
Mar 28 15:51:41.573 DEBG total time, name: chunk-writer, input: 8.775821448, inside: 0.008448979, output: 0.000089112
Mar 28 15:51:41.574 DEBG total time, name: chunk-writer, input: 8.776721937, inside: 0.008206822, output: 0.000087147
Mar 28 15:51:41.574 DEBG total time, name: chunk-writer, input: 8.771950131, inside: 0.011666925, output: 0.000080616
        Command being timed: "/tmp/tmp.YRfyGQboNT/rdedup/target/release/rdedup --dir rdtest/ram -D -D store a"
        User time (seconds): 33.65
        System time (seconds): 0.77
        Percent of CPU this job got: 390%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:08.82
[...]
```
So on my machine, the time taken by the chunker for a 200MB file already in memory is ~2.5s. This is ~3x slower than [rsroll by itself](https://github.com/aidanhs/rollsum-tests) (assuming the benchmarks are approximately correct), so it seems to me that the majority of time here is in the wrapper rdedup has around rsroll - even if the algorithm was 2x faster(!), the overall speedup in the chunking phase would be ~20% at most.

Regarding the output that you've got, I'd be interested to know whether you made sure the file was in RAM or not before running.

**Comment by dpc** [comment]
I'm quite sure I had it in fs cache. I am just dumping 1gb of random data (saved to file from urandom) to an empty repo. The `input` on `input-reader` is supposed to account for time spent on actually reading the data from IO. That's where I want the bottleneck to be. :)

I'm quite interested in benchmarks between different rollsums.

I was also thinking about adding minimum chunk size to `rollsum` library. #88 . Having minimum chunk size allows  skip keeping rollsum for some part of the data. Doing no work at all is a great speedup for any algorithm.

**Comment by dpc** [comment]
Let's move performance discussion to #92

**Pull request merged**
