### PR TITLE
Fix Lint Warnings and Add Linting to CI

### PR DESCRIPTION
**Pull request by phillipCouto**
Related to #69.

### CODE REVIEW

**Comment by dpc** [comment]
Does this actually fail on mismatch / unfixed problems?

**Comment by phillipCouto** [comment]
I am looking into it now.

**Comment by phillipCouto** [comment]
I have added caching to the CI config to improve the build time as building rustfmt and clippy take a substantial amount of time. I am thinking of including the libsodium build as well, this will save another minute or two from the runs.

**Comment by phillipCouto** [comment]
This will close #69.

**Comment by phillipCouto** [comment]
@dpc ok I think this is settled now lol. This was more work than intended but we now have clippy and rustfmt checking with caching to reduce CI job times as well.

For some reason I couldn't get libsodium build to cache between builds. We can do it in another PR.

**Comment by phillipCouto** [comment]
@dpc can you review once more to make sure this is still a sound PR?

**Pull request merged**
